//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GruppL_IK073G_ht19.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Expertises
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Expertises()
        {
            this.Person_Expertise = new HashSet<Person_Expertise>();
        }
    
        [ScaffoldColumn(false)]
        public int Expertise_id { get; set; }
        public string Expertise { get; set; }
        [ScaffoldColumn(false)]
        public Nullable<int> Competence_id { get; set; }
    
        public virtual Competences Competences { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Person_Expertise> Person_Expertise { get; set; }
    }
}
