//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GruppL_IK073G_ht19.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class key_abilitiy
    {
        public int key_abilitiy_id { get; set; }
        public int person_id { get; set; }
        public string abilitiy { get; set; }
    
        public virtual Persons Persons { get; set; }
    }
}
